@startuml
interface Stopable {
}
abstract class AbstractElasticJob {
	abstract void executeJob();
}
abstract class AbstractSaturnJob {
    abstract Map handleJob();
    abstract SaturnJobReturn doExecution();
}
abstract class CrondJob {
}
abstract class OnetimeJob {
}
class SaturnJavaJob {
    SaturnJobReturn handleJavaJob();
}
class SaturnScriptJob {
}


Stopable  <|--  AbstractElasticJob
AbstractElasticJob  <|--  AbstractSaturnJob
AbstractSaturnJob  <|--  CrondJob
AbstractSaturnJob  <|--  OnetimeJob
CrondJob  <|--  SaturnJavaJob
CrondJob  <|--  SaturnScriptJob

@enduml